// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.bufunfa.finance.ui.transacao;

import java.io.Serializable;

privileged aspect TransacaoView_Roo_Serializable {
    
    declare parents: TransacaoView implements Serializable;
    
}
