// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.bufunfa.finance.ui.conta;

import java.io.Serializable;

privileged aspect ContaView_Roo_Serializable {
    
    declare parents: ContaView implements Serializable;
    
}
